### ISSUE TITLE
Multiple ratings instances affect each other stars.

### ISSUE THREAD

**Issue by evgeniyftw** [shahronak47/shinyRatings#15]
A reproducible example where the first rating will be 5 stars by default instead of 0.5:

```
library(shiny)

ui <- fluidPage(
           div("Rating 1:", shinyRatings::shinyRatings("rating1", default = 0.5)),
           div("Rating 2:", shinyRatings::shinyRatings("rating2", default = 0.5))
)

# Define server logic required to draw a histogram
server <- function(input, output) {
}

# Run the application
shinyApp(ui = ui, server = server)
```

**Comment by shahronak47** [comment]
Hi @evgeniyftw , Thank you for creating the issue. I have a fix ready at https://github.com/shahronak47/shinyRatings/pull/16 which I will merge soon. In the meantime, could you test if the fix works for you? You can download the branch using the following command. 

```
devtools::install_github('shahronak47/shinyRatings@14-multiple-stars')
```

**Comment by shahronak47** [comment]
This has been released to `master` branch so  installing it would now be `devtools::install_github('shahronak47/shinyRatings')
`

**Comment by evgeniyftw** [comment]
Hi @shahronak47, thank you for implementing the fix. It works!
