### ISSUE TITLE
Make stars interactivity fixed when disable = TRUE

### ISSUE THREAD

**Issue by cwilligv** [shahronak47/shinyRatings#20]
First of all, thanks for the package, it's really nice to have this functionality available in Shiny.

I'm using it to show a score that the user can't change so I've set up the parameter disable = TRUE. However, the user can still interact with the ratings component changing the stars up and down, although it doesn't change the rating it looks like something is broken. Is it possible to disable that interactivity as well?

Cheers.

**Comment by shahronak47** [comment]
Hi @cwilligv , thank you for reporting the issue. I have a fix ready in this PR #21 which I will merge in couple of days. 

In the meantime, if you have time would you mind testing it out by installing the branch

```
devtools::install_github('shahronak47/shinyRatings@20-disable-interactivity')
```

**Comment by shahronak47** [comment]
This has now been merged to the master branch. Not planning to submit it to CRAN yet but can be downloaded from Github.

**Comment by cwilligv** [comment]
Thanks @shahronak47 , I have installed the github version of the package and I can see it's working. Interactivity is blocked when disable = TRUE.
Cheers.
