### ISSUE TITLE
shinyRatings inside Card object from bslib not working

### ISSUE THREAD

**Issue by cwilligv** [shahronak47/shinyRatings#22]
Hi,

I'm using shinyRatings within an app that is implemented with bslib components. In particular when I use shinyRatings inside a card the stars don't get updated.

For example, if I run this code from the console in RStudio:
`library(bslib)` 
`card(shinyRatings(inputId = "star1", no_of_stars = 5, default = 0.5, disabled = TRUE))`

I get this as output:
![image](https://github.com/shahronak47/shinyRatings/assets/11884925/98982e98-0a2e-4ada-8236-971f83c013f1)

Any ideas?

**Comment by cwilligv** [comment]
This might be related to my issue, the html code behind shinyRatings uses <html> and <body> tags which might not work properly with card.

**Comment by shahronak47** [comment]
Hi @cwilligv , `shinyRatings` need to be part of some kind of page like `fluidPage`. If you are using `bslib` you may try `page_fluid`. Try this - 

```
library(shiny)
library(shinyRatings)
library(bslib)

ui <- page_fluid(
  card(shinyRatings(inputId = "star1", no_of_stars = 5, default = 0.5, disabled = TRUE))
)

server <- function(input, output, session) {
  
}

shinyApp(ui, server)
```
