### ISSUE TITLE
Make the initial value and number of stars aligned. 

### ISSUE THREAD

**Issue by shahronak47** [shahronak47/shinyRatings#3]
```
library(shiny)
library(shinyRatings)

ui <- fluidPage(
  shinyRatings('star'), 
  textOutput('text')
)

server <- function(input, output, session) {
  output$text <- renderText({paste("No. of stars : ", input$star)})
}

shinyApp(ui, server)
```

When you launch the application this is what you see - 

<img width="197" alt="image" src="https://user-images.githubusercontent.com/10164875/218247589-ee453f32-3b47-4a3a-a91b-b457cf684d95.png">

The number of stars selected by default (5) is not the same as the number of stars shown in `input$star` (0).  After the initialization, everything works smoothly but this needs to be fixed.

**Comment by magic-leo** [comment]
Really like this package! If you can fix this bug I'll definitely use it in my app :) 

Hope it gets resolved soon! Good work

**Comment by shahronak47** [comment]
@magic-leo Thank you for trying the package out. I have fixed this bug and it has been updated in the `master` branch. You can try this out and let me know if it works as expected for you.

**Comment by magic-leo** [comment]
Thank you so much! Looks good.

One more thing, it appears that whenever the feedback comes up on screen all other text in my app gets aligned to the centre. Would you know how to fix that?

**Comment by shahronak47** [comment]
Can you create a new issue with a small reproducible example that I can test?
